### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dolzhenko-tony** [arhelmus/gloryforukraine#10]
<img width="892" alt="Screenshot 2022-03-01 at 17 53 00" src="https://user-images.githubusercontent.com/5227857/156202066-c8d302b7-edfe-47e3-ad25-a12ed77c8fae.png">

**Comment by arhelmus** [comment]
what do you see when run this from a terminal?

curl https://gloryforukraine.pages.dev/scheduled_targets.json

**Comment by maliarov** [comment]
невдала спроба с json
