### ISSUE TITLE
Щось не працює на останнії версій - постійні таймаути

### ISSUE THREAD

**Issue by sprilukin** [arhelmus/gloryforukraine#9]
![Screenshot 2022-03-01 at 17 17 30](https://user-images.githubusercontent.com/1129834/156195775-bc88e7bc-550f-461d-9f40-1d6a8b11b81b.png)

**Comment by dumavit** [comment]
думаю ціі сайти або забанили твоє айпі або вже недоступні звідси

**Comment by maliarov** [comment]
бомбардір робє репорт напрікінці, основна масса запросів працюе
